export function basicTemplateFrom({ prompt, appType, template }) {
  const title = `${template} ${appType}`;
  const desc = prompt;
  const bg = template === 'Portfolio' ? 'from-indigo-500 to-purple-500' :
             template === 'Business' ? 'from-gray-700 to-gray-900' :
             template === 'Blog' ? 'from-rose-500 to-orange-400' :
             'from-emerald-500 to-teal-500';

  const indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="styles.css" />
</head>
<body class="min-h-screen bg-gradient-to-br ${bg} text-white">
  <header class="p-6">
    <h1 class="text-3xl font-bold">${title}</h1>
    <p class="opacity-90">${desc}</p>
  </header>
  <main id="app" class="p-6 grid gap-6"></main>
  <footer class="p-6 opacity-80">Generated by AI Builder</footer>
  <script src="app.js"></script>
</body>
</html>`;

  const stylesCss = `/* Add your custom styles here */\n.card{background:rgba(255,255,255,0.1);border-radius:12px;padding:16px}`;

  const appJs = `const data = [
  { title: 'Feature One', text: 'Quickly scaffold apps.' },
  { title: 'Feature Two', text: 'Customize templates easily.' },
  { title: 'Export', text: 'Download or host anywhere.' }
];
const container = document.getElementById('app');
container.innerHTML = data.map(function(d){
  return '<div class="card">\n' +
         '  <h2 class="text-xl font-semibold">${template} - ${appType}: ' + d.title + '</h2>\n' +
         '  <p class="opacity-90">' + d.text + '</p>\n' +
         '</div>';
}).join('');
`;

  return [
    { path: 'index.html', content: indexHtml },
    { path: 'styles.css', content: stylesCss },
    { path: 'app.js', content: appJs },
  ];
}